name: markdown_fl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_html_table: ^3.0.0
  http: ^1.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Fira Mono
      fonts:
        - asset: fonts/FiraMono-Regular.ttf
        - asset: fonts/FiraMono-Medium.ttf
          weight: 500
        - asset: fonts/FiraMono-Bold.ttf
          weight: 700
